In [1]:
import numpy as np

In [5]:
a = np.zeros((2,2))
a

array([[0., 0.],
       [0., 0.]])

In [7]:
b = np.ones((2,2))
b

array([[1., 1.],
       [1., 1.]])

In [17]:
a = np.array([1,2,3,4]).reshape(2,2)
a

array([[1, 2],
       [3, 4]])

In [18]:
b = np.array([2,2,2,2]).reshape(2,2)
b

array([[2, 2],
       [2, 2]])

In [19]:
a + b

array([[3, 4],
       [5, 6]])

In [20]:
a-b

array([[-1,  0],
       [ 1,  2]])

The next idea is to have two np arrays
a is shape 3,3
b is shape 1,3

The idea is to iterate through the rows of a and b
for each row in a every element should be subtracted by the corresponding column of b
a[0,0] - b[0]
a[0,1] - b[0]
a[1,0] - b[1] ...

The operations are then
[
[0-0,1-0,2-0],
[3-1,4-1,5-1],
[6-2,7-2,8-2]
]

the result should then become
[
[0,1,2],
[2,3,4],
[4,5,6]
]

In [32]:
a = np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [33]:
b = np.arange(3).reshape(1,3)
b

array([[0, 1, 2]])

In [46]:
c = np.empty((3,3))
for i,a2 in enumerate(a):
    c[i] = (a2 - b[0,i])
c

array([[0., 1., 2.],
       [2., 3., 4.],
       [4., 5., 6.]])