In [30]:
import numpy as np
import pandas as pd

In [31]:
wp = float('-inf')  # wall punish
# columns: up, down, left, right
# rows: states
r = np.matrix([
    [wp, 0, wp, 0],  # 1
    [wp, 0, 0, -10],  # 2
    [wp, 100, 0, wp],  # 3
    [0, wp, wp, 0],  # 4
    [0, wp, 0, 100],  # 5
    [-10, wp, 0, wp],  # 6
])
r

matrix([[-inf,   0., -inf,   0.],
        [-inf,   0.,   0., -10.],
        [-inf, 100.,   0., -inf],
        [  0., -inf, -inf,   0.],
        [  0., -inf,   0., 100.],
        [-10., -inf,   0., -inf]])

In [43]:
# columns: up, down, left, right
# rows: states
q_table = np.zeros((6, 4))
q_table

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [33]:
df = 0.9
lr = 1

In [34]:
s1, s2, s3, s4, s5, s6 = 0, 1, 2, 3, 4, 5
up, down, left, right = 0, 1, 2, 3

In [35]:
def get_new_q(state,action,next_state):
    reward = r[state, action] # reward for current state
    max_next = np.max(q_table[next_state, :]) # max for all actions of next state
    new_q = reward + df * max_next # new q for q-table
    print('reward: ', reward)
    print('max_next: ', max_next)
    print('new_q: ', new_q)
    return new_q

The robot is placed in state 4 first and consider a move to 5. Calculate the new Q-value for this state-action pair and update the Q matrix.


In [36]:
state = s4
action = right
next_state = s5

q_table[state, action] = get_new_q(state,action,next_state)
print('q table:\n',q_table)

reward:  0.0
max_next:  0.0
new_q:  0.0
q table:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


The robot is placed in state 5 and consider the move to 6. Calculate the new Q-value for this state-action pair and update the Q matrix.

In [37]:
state = s5
action = right
next_state = s6

q_table[state, action] = get_new_q(state,action,next_state)
print('q table:\n', q_table)

reward:  100.0
max_next:  0.0
new_q:  100.0
q table:
 [[  0.   0.   0.   0.]
 [  0.   0.   0.   0.]
 [  0.   0.   0.   0.]
 [  0.   0.   0.   0.]
 [  0.   0.   0. 100.]
 [  0.   0.   0.   0.]]


The robot is placed in state 4 again and considers the move to 5. Calculate the new Q-value for this state-action pair and update the Q matrix.


In [38]:
state = s4
action = right
next_state = s5

q_table[state, action] = get_new_q(state,action,next_state)
print('q table:\n', q_table)

reward:  0.0
max_next:  100.0
new_q:  90.0
q table:
 [[  0.   0.   0.   0.]
 [  0.   0.   0.   0.]
 [  0.   0.   0.   0.]
 [  0.   0.   0.  90.]
 [  0.   0.   0. 100.]
 [  0.   0.   0.   0.]]


The robot is placed in state 1 and consider the move to 4. Calculate the new Q-value for this state-action pair and update the Q matrix.

In [39]:
state = s1
action = down
next_state = s4

q_table[state, action] = get_new_q(state,action,next_state)
print('q table:\n', q_table)

reward:  0.0
max_next:  90.0
new_q:  81.0
q table:
 [[  0.  81.   0.   0.]
 [  0.   0.   0.   0.]
 [  0.   0.   0.   0.]
 [  0.   0.   0.  90.]
 [  0.   0.   0. 100.]
 [  0.   0.   0.   0.]]


Based on the information entered, which path is the most likely choice of the robot at this stage when dropped in zone 2?

Checking new q's for different actions

In [40]:
state = s2
action = left
next_state = s1

new_q = get_new_q(state,action,next_state)
print('new_q:', new_q)

reward:  0.0
max_next:  81.0
new_q:  72.9
new_q: 72.9


In [41]:
state = s2
action = right
next_state = s3

new_q = get_new_q(state,action,next_state)
print('new_q:', new_q)

reward:  -10.0
max_next:  0.0
new_q:  -10.0
new_q: -10.0


In [42]:
state = s2
action = down
next_state = s5

new_q = get_new_q(state,action,next_state)
print('new_q:', new_q)

reward:  0.0
max_next:  100.0
new_q:  90.0
new_q: 90.0


The highest q is action down so that is the most likely choice