In [63]:
import numpy as np

### 1 - Construct R and Q matrix

In [64]:
q = np.zeros((2,3))
r = np.array([[0,0,-10],[0,0,100]])
df = 0.9
lr = 1

In [65]:
q

array([[0., 0., 0.],
       [0., 0., 0.]])

In [66]:
r

array([[  0,   0, -10],
       [  0,   0, 100]])

In [67]:
class Action:
    def __init__(self):
        self.Q = None
        self.next_state = None

class Agent:
    def __init__(self):
        self.state = None
        self.action = Action()



In [68]:
def updateQ(s, a):
    q[s][a] += lr * r[s][a] + df * max(q[s][:])

### 2 The robot is placed in state 4 first and consider a move to 5. Calculate the new Q-value for this state-action pair and update the Q matrix.


In [69]:
updateQ(0,1)
q

array([[0., 0., 0.],
       [0., 0., 0.]])

### 3 The robot is placed in state 5 and consider the move to 6. Calculate the new Q-value for this state-action pair and update the Q matrix.



In [70]:
updateQ(0,2)
q

array([[  0.,   0., -10.],
       [  0.,   0.,   0.]])

### 4: The robot is placed in state 4 again and considers the move to 5. Calculate the new Q-value for this state-action pair and update the Q matrix.



In [71]:
updateQ(0,0)
q

array([[  0.,   0., -10.],
       [  0.,   0.,   0.]])

### 5: The robot is placed in state 1 and consider the move to 4. Calculate the new Q-value for this state-action pair and update the Q matrix.


In [73]:
updateQ(0,1)
q

array([[  0.,   0., -10.],
       [  0.,   0.,   0.]])

### 6: Based on the information entered, which path is the most likely choice of the robot at this stage when dropped in zone 2?
